"use client";

import { useState, useEffect, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronLeft, ChevronRight, Calendar as CalIcon, Sparkles, Loader2, X, Trash2 } from "lucide-react";
import { plannerApi, outfitsApi } from "@/lib/api";

type PlannerEvent = {
  id: number;
  event_date: string; // YYYY-MM-DD
  title: string;
  outfit_items: string[];
};

function startOfWeek(d: Date) {
  const day = d.getDay(); // 0 = Sun
  const diff = day === 0 ? -6 : 1 - day; // week starts Monday
  const s = new Date(d);
  s.setDate(d.getDate() + diff);
  s.setHours(0, 0, 0, 0);
  return s;
}

function toISODate(d: Date) {
  return d.toISOString().slice(0, 10);
}

export default function PlannerPage() {
  const [weekStart, setWeekStart] = useState(() => startOfWeek(new Date()));
  const [events, setEvents] = useState<PlannerEvent[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeDate, setActiveDate] = useState<string | null>(null);
  const [title, setTitle] = useState("");
  const [generating, setGenerating] = useState(false);

  const weekDates = useMemo(
    () => Array.from({ length: 7 }, (_, i) => {
      const d = new Date(weekStart);
      d.setDate(weekStart.getDate() + i);
      return d;
    }),
    [weekStart]
  );

  const monthLabel = weekStart.toLocaleDateString(undefined, { month: "long", year: "numeric" });

  async function fetchEvents() {
    try {
      const data = await plannerApi.getEvents();
      setEvents(data.events || []);
    } catch (err) {
      console.error("Failed to load planner events", err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    fetchEvents();
  }, []);

  const eventFor = (iso: string) => events.find((e) => e.event_date === iso);

  // One input only: a title. The outfit itself is auto-generated by the AI
  // stylist using sensible defaults, rather than asking the user to pick items.
  const handleCreate = async () => {
    if (!activeDate || !title.trim()) return;
    setGenerating(true);
    try {
      const outfit = await outfitsApi.generate({
        mood: "Refined",
        occasion: title,
        budget: 5000,
      });
      const itemNames: string[] = (outfit.items || []).map((i: { name: string }) => i.name);
      await plannerApi.createEvent({
        event_date: activeDate,
        title,
        outfit_items: itemNames,
      });
      setActiveDate(null);
      setTitle("");
      await fetchEvents();
    } catch (err) {
      console.error("Failed to create planner event", err);
    } finally {
      setGenerating(false);
    }
  };

  const handleDelete = async (id: number) => {
    setEvents((prev) => prev.filter((e) => e.id !== id));
    try {
      await plannerApi.deleteEvent(id);
    } catch (err) {
      console.error("Failed to delete event", err);
      fetchEvents();
    }
  };

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center text-primary">
        <Loader2 className="w-8 h-8 animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in h-full flex flex-col">
      <header className="flex justify-between items-end">
        <div>
          <h1 className="text-4xl font-display font-medium tracking-tight mb-2">Outfit Planner</h1>
          <p className="text-foreground/60">Add an outfit or event to a day — build your week so you know what you&apos;re wearing before you wake up.</p>
        </div>
        <div className="flex items-center gap-4 bg-surface rounded-full px-2 py-1 border border-border">
          <button
            onClick={() => setWeekStart((d) => { const n = new Date(d); n.setDate(d.getDate() - 7); return n; })}
            className="p-2 hover:bg-[#595800]/8 rounded-full transition-colors"
          >
            <ChevronLeft className="w-5 h-5" />
          </button>
          <span className="font-medium px-4">{monthLabel}</span>
          <button
            onClick={() => setWeekStart((d) => { const n = new Date(d); n.setDate(d.getDate() + 7); return n; })}
            className="p-2 hover:bg-[#595800]/8 rounded-full transition-colors"
          >
            <ChevronRight className="w-5 h-5" />
          </button>
        </div>
      </header>

      {/* Week Grid */}
      <div className="grid grid-cols-7 gap-4 flex-1">
        {weekDates.map((d) => {
          const iso = toISODate(d);
          const isToday = iso === toISODate(new Date());
          const ev = eventFor(iso);

          return (
            <div key={iso} className="flex flex-col h-full gap-4">
              <div className={`text-center pb-4 border-b ${isToday ? "border-primary" : "border-border"}`}>
                <p className="text-xs text-foreground/50 uppercase tracking-wider mb-1">
                  {d.toLocaleDateString(undefined, { weekday: "short" })}
                </p>
                <p className={`text-xl font-medium ${isToday ? "text-primary" : ""}`}>{d.getDate()}</p>
              </div>

              {ev ? (
                <div className="flex-1 glass-panel rounded-2xl p-4 flex flex-col group relative">
                  <button
                    onClick={() => handleDelete(ev.id)}
                    className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity p-1.5 rounded-lg hover:bg-[#595800]/8 text-foreground/40 hover:text-red-400"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                  <div className="flex-1 flex flex-col items-center justify-center text-center px-2">
                    <Sparkles className="w-5 h-5 text-primary mb-2" />
                    <p className="text-xs font-medium">{ev.title}</p>
                    {ev.outfit_items?.length > 0 && (
                      <p className="text-[10px] text-foreground/40 mt-1 line-clamp-2">
                        {ev.outfit_items.join(", ")}
                      </p>
                    )}
                  </div>
                </div>
              ) : (
                <button
                  onClick={() => setActiveDate(iso)}
                  className="flex-1 glass-panel rounded-2xl p-4 flex flex-col items-center justify-center border-dashed hover:border-solid hover:bg-[#595800]/5 transition-all group"
                >
                  <div className="text-foreground/30 group-hover:text-primary transition-colors flex flex-col items-center">
                    <CalIcon className="w-6 h-6 mb-2" />
                    <span className="text-xs font-medium">Plan Outfit</span>
                  </div>
                </button>
              )}
            </div>
          );
        })}
      </div>

      {/* Single-input event creation */}
      <AnimatePresence>
        {activeDate && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4"
            onClick={() => !generating && setActiveDate(null)}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 10 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 10 }}
              onClick={(e) => e.stopPropagation()}
              className="glass-panel rounded-3xl p-6 w-full max-w-md relative"
            >
              <button
                onClick={() => setActiveDate(null)}
                className="absolute top-6 right-6 text-foreground/40 hover:text-foreground"
              >
                <X className="w-5 h-5" />
              </button>
              <h3 className="text-2xl font-display font-medium mb-1">Plan an Outfit</h3>
              <p className="text-sm text-foreground/50 mb-6">
                Just name the occasion — FitSense picks the outfit for you.
              </p>
              <div className="space-y-4">
                <input
                  autoFocus
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g. Office Mix, Date Night, Client Meeting"
                  className="w-full bg-background border border-border rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-primary/50 transition-colors"
                  onKeyDown={(e) => e.key === "Enter" && handleCreate()}
                />
                <button
                  onClick={handleCreate}
                  disabled={generating || !title.trim()}
                  className="w-full bg-primary text-primary-foreground py-3 rounded-xl font-medium text-sm flex items-center justify-center gap-2 hover:opacity-90 transition-opacity disabled:opacity-50"
                >
                  {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                  {generating ? "Styling..." : "Generate & Schedule"}
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}